import type { AssistantContext } from "@/lib/assistant-types";
import type { ControlPlaneRequest } from "@/lib/controlplane";

export type RequestInspectionRecord = ControlPlaneRequest;

export const previewRequestRecords: RequestInspectionRecord[] = [
  {
    id: "req_preview_01",
    tunnel_id: "tun_preview_app_01",
    tunnel_subdomain: "app-preview",
    kind: "REQUEST",
    method: "GET",
    path: "/api/health",
    status: 200,
    duration_ms: 42,
    source: "public ingress from 52.41.22.12:443",
    target: "http://localhost:3000",
    destination: "localhost:3000 -> Next.js route handler",
    request_headers: ["accept: application/json", "user-agent: curl/8.7.1"],
    response_headers: ["content-type: application/json"],
    request_preview: "GET /api/health | accept: application/json | user-agent: curl/8.7.1",
    response_preview: '{"status":"ok","region":"local"}',
    created_at: "2026-03-31T09:42:10.000Z",
  },
  {
    id: "req_preview_02",
    tunnel_id: "tun_preview_app_01",
    tunnel_subdomain: "app-preview",
    kind: "REQUEST",
    method: "POST",
    path: "/api/checkout",
    status: 500,
    duration_ms: 624,
    source: "public ingress from 34.77.18.11:443",
    target: "http://localhost:3000",
    destination: "localhost:3000 -> checkout service",
    error_type: "UPSTREAM_SERVER_ERROR",
    request_headers: [
      "content-type: application/json",
      "user-agent: insomnia/2026.1",
      "x-request-id: req_9ad2",
    ],
    response_headers: ["content-type: application/json"],
    request_preview:
      "POST /api/checkout | content-type: application/json | x-request-id: req_9ad2",
    payload_preview:
      '{ "plan": "pro", "customerEmail": "dev@example.com", "workspaceId": "ws_demo" }',
    response_preview:
      '{"error":"database transaction rolled back","hint":"missing customer record"}',
    created_at: "2026-03-31T09:38:44.000Z",
  },
  {
    id: "req_preview_03",
    tunnel_id: "tun_preview_docs_02",
    tunnel_subdomain: "docs-lab",
    kind: "REQUEST",
    method: "GET",
    path: "/favicon.ico",
    status: 404,
    duration_ms: 18,
    source: "public ingress from 18.196.14.80:443",
    target: "http://localhost:5173",
    destination: "localhost:5173 -> static dev server",
    error_type: "ROUTE_NOT_FOUND",
    request_headers: ["accept: image/avif,image/webp,*/*", "user-agent: Chrome/135.0"],
    response_headers: ["content-type: text/plain; charset=utf-8"],
    request_preview: "GET /favicon.ico | accept: image/avif,image/webp,*/*",
    response_preview: "Not Found",
    created_at: "2026-03-31T09:33:05.000Z",
  },
  {
    id: "req_preview_04",
    tunnel_id: "tun_preview_hooks_03",
    tunnel_subdomain: "hooks-preview",
    kind: "WEBHOOK",
    provider: "Stripe",
    event_type: "payment_intent.payment_failed",
    method: "POST",
    path: "/api/webhooks/stripe",
    status: 400,
    duration_ms: 212,
    source: "public ingress from 3.18.12.63:443",
    target: "http://localhost:3000",
    destination: "localhost:3000 -> Stripe webhook route",
    error_type: "SIGNATURE_VERIFICATION_FAILED",
    request_headers: [
      "content-type: application/json",
      "stripe-signature: t=1711877001,v1=54c3...",
    ],
    response_headers: ["content-type: text/plain; charset=utf-8"],
    request_preview:
      "POST /api/webhooks/stripe | content-type: application/json | stripe-signature: t=1711877001,v1=54c3...",
    payload_preview:
      '{ "type": "payment_intent.payment_failed", "data": { "object": { "id": "pi_123" } } }',
    response_preview: "Webhook signature verification failed",
    created_at: "2026-03-31T09:27:51.000Z",
  },
  {
    id: "req_preview_05",
    tunnel_id: "tun_preview_hooks_03",
    tunnel_subdomain: "hooks-preview",
    kind: "WEBHOOK",
    provider: "GitHub",
    event_type: "push",
    method: "POST",
    path: "/api/webhooks/github",
    status: 202,
    duration_ms: 96,
    source: "public ingress from 140.82.112.1:443",
    target: "http://localhost:3000",
    destination: "localhost:3000 -> queue-backed GitHub consumer",
    request_headers: [
      "content-type: application/json",
      "x-github-event: push",
      "x-hub-signature-256: sha256=34fd...",
    ],
    response_headers: ["content-type: application/json"],
    request_preview:
      "POST /api/webhooks/github | x-github-event: push | x-hub-signature-256: sha256=34fd...",
    payload_preview:
      '{ "ref": "refs/heads/main", "repository": { "full_name": "acme/binboi" } }',
    response_preview: '{"accepted":true,"queued":true}',
    created_at: "2026-03-31T09:21:29.000Z",
  },
  {
    id: "req_preview_06",
    tunnel_id: "tun_preview_app_01",
    tunnel_subdomain: "app-preview",
    kind: "REQUEST",
    method: "PUT",
    path: "/api/projects/p_01/settings",
    status: 422,
    duration_ms: 141,
    source: "public ingress from 52.41.22.12:443",
    target: "http://localhost:3000",
    destination: "localhost:3000 -> settings route",
    error_type: "PAYLOAD_REJECTED",
    request_headers: ["content-type: application/json", "x-request-id: req_41bd"],
    response_headers: ["content-type: application/json"],
    request_preview: "PUT /api/projects/p_01/settings | content-type: application/json",
    payload_preview: '{ "retentionDays": -3, "auditMode": true }',
    response_preview: '{"error":"retentionDays must be greater than zero"}',
    created_at: "2026-03-31T09:14:16.000Z",
  },
  {
    id: "req_preview_07",
    tunnel_id: "tun_preview_lab_04",
    tunnel_subdomain: "latency-lab",
    kind: "REQUEST",
    method: "GET",
    path: "/stream/status",
    status: 503,
    duration_ms: 8,
    source: "public ingress from 13.224.198.10:443",
    target: "http://localhost:8080",
    destination: "localhost:8080 -> Go API service",
    error_type: "SERVICE_UNAVAILABLE",
    request_headers: ["accept: text/event-stream", "user-agent: Firefox/127.0"],
    response_headers: ["content-type: text/plain; charset=utf-8"],
    request_preview: "GET /stream/status | accept: text/event-stream",
    response_preview: "Tunnel stream unavailable.",
    created_at: "2026-03-31T09:09:03.000Z",
  },
  {
    id: "req_preview_08",
    tunnel_id: "tun_preview_lab_04",
    tunnel_subdomain: "latency-lab",
    kind: "REQUEST",
    method: "GET",
    path: "/",
    status: 200,
    duration_ms: 64,
    source: "public ingress from 54.211.92.21:443",
    target: "http://localhost:8080",
    destination: "localhost:8080 -> Go API service",
    request_headers: ["accept: text/html", "user-agent: Safari/17.4"],
    response_headers: ["content-type: text/html; charset=utf-8"],
    request_preview: "GET / | accept: text/html",
    response_preview: "<html><body>hello from the preview relay</body></html>",
    created_at: "2026-03-31T09:02:37.000Z",
  },
];

export function normalizeRequestRecord(record: RequestInspectionRecord): RequestInspectionRecord {
  return {
    ...record,
    kind: record.kind || "REQUEST",
    source: record.source || "public ingress",
    target: record.target || record.destination || "Unknown target",
    destination: record.destination || record.target || "Unknown destination",
    request_headers: record.request_headers ?? [],
    response_headers: record.response_headers ?? [],
    request_preview: record.request_preview || `${record.method} ${record.path}`,
    payload_preview: record.payload_preview || "",
    response_preview: record.response_preview || "",
  };
}

export function buildAssistantContextForRequest(
  record: RequestInspectionRecord,
): AssistantContext {
  const normalized = normalizeRequestRecord(record);
  const isWebhook =
    normalized.kind === "WEBHOOK" || Boolean(normalized.provider) || normalized.path.includes("webhook");

  return {
    requestContext: {
      method: normalized.method,
      path: normalized.path,
      status: normalized.status,
      durationMs: normalized.duration_ms,
      provider: normalized.provider,
      source: normalized.source,
      target: normalized.target,
      destination: normalized.destination,
      errorType: normalized.error_type,
      requestPreview: normalized.request_preview,
      responsePreview: normalized.response_preview,
      tunnelId: normalized.tunnel_id,
      timestamp: normalized.created_at,
      summary: `${normalized.method} ${normalized.path} returned ${normalized.status} after ${normalized.duration_ms}ms on tunnel ${normalized.tunnel_subdomain}.`,
    },
    webhookContext: isWebhook
      ? {
          provider: normalized.provider,
          eventType: normalized.event_type,
          endpoint: normalized.path,
          deliveryStatus: normalized.status >= 400 ? "FAILED" : "SUCCESS",
          latencyMs: normalized.duration_ms,
          destination: normalized.destination,
          receivedAt: normalized.created_at,
          errorClassification: normalized.error_type,
          payloadPreview: normalized.payload_preview,
          responsePreview: normalized.response_preview,
          attemptId: normalized.id,
          summary: normalized.provider
            ? `${normalized.provider} webhook request is being inspected from the requests workbench.`
            : `Webhook-like request ${normalized.method} ${normalized.path} is being inspected from the requests workbench.`,
        }
      : undefined,
  };
}
