version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: binboi
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: binboi_db
    ports:
      - "5432:5432"

  core:
    build: .
    ports:
      - "8080:8080" # API
      - "8081:8081" # Tunnel TCP
      - "8000:8000" # Proxy HTTP
    environment:
      DATABASE_URL: postgres://binboi:your_password@db:5432/binboi_db
    depends_on:
      - db