version: '3.8'

services:
  # Binboi Server Simülasyonu
  binboi-server:
    build: .
    ports:
      - "80:80"       # Public HTTP Router
      - "8080:8080"   # Tunnel Listener
    environment:
      - AUTH_TOKEN=miransas-secret-2026
      - DB_URL=postgres://user:pass@db:5432/binboi
    networks:
      - binboi-network

  # İleride kuracağımız Veritabanı (Şimdiden hazır olsun)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: binboi
    ports:
      - "5432:5432"
    networks:
      - binboi-network

networks:
  binboi-network:
    driver: bridge